DROP TABLE IF EXISTS `member_user_rights`;
CREATE TABLE `member_user_rights` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户权益编号',
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `rights_type` tinyint NOT NULL COMMENT '权益类型：1次卡 2套餐 3课时 4服务包',
  `rights_code` varchar(64) NOT NULL COMMENT '权益编码',
  `rights_name` varchar(128) NOT NULL COMMENT '权益名称',
  `product_id` bigint DEFAULT NULL COMMENT '关联商品SPU ID',
  `sku_id` bigint DEFAULT NULL COMMENT '关联商品SKU ID',
  `total_count` int NOT NULL DEFAULT 0 COMMENT '累计发放次数',
  `used_count` int NOT NULL DEFAULT 0 COMMENT '累计已使用次数',
  `refund_count` int NOT NULL DEFAULT 0 COMMENT '累计退款回退次数',
  `adjust_count` int NOT NULL DEFAULT 0 COMMENT '累计人工调整次数',
  `remain_count` int NOT NULL DEFAULT 0 COMMENT '当前剩余次数',
  `freeze_count` int NOT NULL DEFAULT 0 COMMENT '冻结次数',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1正常 2冻结 3失效 4用尽',
  `activate_time` datetime DEFAULT NULL COMMENT '生效时间',
  `expire_time` datetime DEFAULT NULL COMMENT '失效时间',
  `last_consume_time` datetime DEFAULT NULL COMMENT '最后消费时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `createtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `updatetime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenantid` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_user_rights_code` (`rights_code`) USING BTREE,
  UNIQUE KEY `uk_user_product` (`user_id`, `rights_type`, `product_id`, `sku_id`, `deleted`) USING BTREE,
  KEY `idx_user_status` (`user_id`, `status`) USING BTREE,
  KEY `idx_expire_time` (`expire_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员用户权益总表';

DROP TABLE IF EXISTS `member_user_rights_log`;
CREATE TABLE `member_user_rights_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '权益流水编号',
  `rights_id` bigint NOT NULL COMMENT '用户权益编号',
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `change_no` varchar(64) NOT NULL COMMENT '变动流水号',
  `change_type` tinyint NOT NULL COMMENT '变动类型：1购买发放 2消费扣减 3退款回退 4后台增加 5后台扣减 6过期清零 7冻结 8解冻',
  `change_count` int NOT NULL COMMENT '本次变动次数，正数增加，负数减少',
  `before_count` int NOT NULL COMMENT '变动前剩余次数',
  `after_count` int NOT NULL COMMENT '变动后剩余次数',
  `biz_type` tinyint NOT NULL COMMENT '业务类型：1订单 2售后 3核销 4后台',
  `biz_id` bigint DEFAULT NULL COMMENT '业务单据ID',
  `biz_no` varchar(64) DEFAULT NULL COMMENT '业务单号',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_user_type` tinyint DEFAULT NULL COMMENT '操作人类型',
  `operate_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `createtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `updatetime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenantid` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_change_no` (`change_no`) USING BTREE,
  KEY `idx_rights_id` (`rights_id`) USING BTREE,
  KEY `idx_user_operate_time` (`user_id`, `operate_time`) USING BTREE,
  KEY `idx_biz` (`biz_type`, `biz_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员用户权益流水表';

DROP TABLE IF EXISTS `member_user_rights_source`;
CREATE TABLE `member_user_rights_source` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '权益来源编号',
  `rights_id` bigint NOT NULL COMMENT '用户权益编号',
  `source_type` tinyint NOT NULL COMMENT '来源类型：1订单购买 2后台发放 3活动赠送 4退款回退',
  `source_id` bigint DEFAULT NULL COMMENT '来源业务ID',
  `source_item_id` bigint DEFAULT NULL COMMENT '来源业务明细ID',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源单号',
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `grant_count` int NOT NULL DEFAULT 0 COMMENT '本来源发放次数',
  `used_count` int NOT NULL DEFAULT 0 COMMENT '本来源已用次数',
  `remain_count` int NOT NULL DEFAULT 0 COMMENT '本来源剩余次数',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1正常 2已退完 3失效',
  `grant_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发放时间',
  `expire_time` datetime DEFAULT NULL COMMENT '来源失效时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `createtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `updatetime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenantid` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_rights_id` (`rights_id`) USING BTREE,
  KEY `idx_source` (`source_type`, `source_id`) USING BTREE,
  KEY `idx_user_status` (`user_id`, `status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员用户权益来源表';
