DROP TABLE IF EXISTS `trade_order_item_consume`;
CREATE TABLE `trade_order_item_consume` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '消费记录编号',
  `consume_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '消费流水号',
  `order_id` bigint unsigned NOT NULL COMMENT '订单编号',
  `order_item_id` bigint unsigned NOT NULL COMMENT '订单项编号',
  `user_id` bigint unsigned NOT NULL COMMENT '用户编号',
  `spu_id` bigint unsigned NOT NULL COMMENT 'SPU 编号',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU 编号',
  `consume_count` int NOT NULL DEFAULT '1' COMMENT '本次消费次数',
  `status` tinyint NOT NULL DEFAULT '10' COMMENT '消费状态：0待核销 10已核销 20已撤销 30退款回退',
  `verify_type` tinyint NOT NULL DEFAULT '1' COMMENT '核销方式：1门店 2后台 3自动',
  `pickup_store_id` bigint DEFAULT NULL COMMENT '核销门店编号',
  `verify_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '核销码',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人编号',
  `operator_user_type` tinyint DEFAULT '1' COMMENT '操作人类型',
  `consume_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '消费时间',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
  `after_sale_id` bigint unsigned DEFAULT NULL COMMENT '关联售后单编号',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_consume_no` (`consume_no`) USING BTREE,
  KEY `idx_order_item_status` (`order_item_id`, `status`) USING BTREE,
  KEY `idx_order_id` (`order_id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_pickup_store_status` (`pickup_store_id`, `status`) USING BTREE,
  KEY `idx_consume_time` (`consume_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='交易订单项消费记录表';
